#!/usr/bin/env python3
"""Configure Android files generated by `flutter create` for HotelChat."""

from pathlib import Path
import re
import shutil
import sys

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android"
APP_ID = "online.ognispb.hotelchat"
GENERATED_ID = "online.ognispb.hotelchat_mobile"
APP_LABEL = "HotelChat"


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def replace_required(path: Path, patterns: list[tuple[str, str]]) -> None:
    if not path.exists():
        fail(f"File not found: {path}")

    text = path.read_text(encoding="utf-8")
    original = text

    for pattern, replacement in patterns:
        text = re.sub(pattern, replacement, text)

    if text == original:
        fail(f"Expected values were not found in {path}")

    path.write_text(text, encoding="utf-8")


def configure_gradle() -> None:
    kotlin_file = ANDROID / "app" / "build.gradle.kts"
    groovy_file = ANDROID / "app" / "build.gradle"

    if kotlin_file.exists():
        replace_required(
            kotlin_file,
            [
                (
                    r'namespace\s*=\s*["\'][^"\']+["\']',
                    f'namespace = "{APP_ID}"',
                ),
                (
                    r'applicationId\s*=\s*["\'][^"\']+["\']',
                    f'applicationId = "{APP_ID}"',
                ),
                (
                    r'minSdk\s*=\s*flutter\.minSdkVersion',
                    'minSdk = 23',
                ),
            ],
        )
        return

    if groovy_file.exists():
        replace_required(
            groovy_file,
            [
                (
                    r'namespace\s*(?:=)?\s*["\'][^"\']+["\']',
                    f'namespace "{APP_ID}"',
                ),
                (
                    r'applicationId\s+["\'][^"\']+["\']',
                    f'applicationId "{APP_ID}"',
                ),
                (
                    r'minSdkVersion\s+flutter\.minSdkVersion',
                    'minSdkVersion 23',
                ),
            ],
        )
        return

    fail("Android app Gradle file was not generated")


def configure_main_activity() -> None:
    source_root = ANDROID / "app" / "src" / "main"
    candidates = list(source_root.rglob("MainActivity.kt"))
    candidates += list(source_root.rglob("MainActivity.java"))

    if not candidates:
        fail("MainActivity was not generated")

    source = candidates[0]
    extension = source.suffix
    text = source.read_text(encoding="utf-8")
    text = re.sub(
        r'^\s*package\s+[A-Za-z0-9_.]+\s*;?',
        f"package {APP_ID}",
        text,
        count=1,
        flags=re.MULTILINE,
    )

    language_dir = "kotlin" if extension == ".kt" else "java"
    destination = (
        source_root
        / language_dir
        / Path(*APP_ID.split("."))
        / f"MainActivity{extension}"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")

    if source.resolve() != destination.resolve():
        source.unlink()

    # Remove empty generated package directories.
    current = source.parent
    stop = source_root / language_dir
    while current != stop and current.exists():
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent


def configure_manifest() -> None:
    manifest = ANDROID / "app" / "src" / "main" / "AndroidManifest.xml"

    if not manifest.exists():
        fail("AndroidManifest.xml was not generated")

    text = manifest.read_text(encoding="utf-8")
    text = re.sub(
        r'android:label="[^"]*"',
        f'android:label="{APP_LABEL}"',
        text,
        count=1,
    )

    internet_permission = (
        '<uses-permission android:name="android.permission.INTERNET"/>'
    )
    if internet_permission not in text:
        text = text.replace(
            "<manifest",
            "<manifest",
            1,
        )
        closing = text.find(">")
        if closing == -1:
            fail("Malformed AndroidManifest.xml")
        text = (
            text[: closing + 1]
            + "\n    "
            + internet_permission
            + text[closing + 1 :]
        )

    manifest.write_text(text, encoding="utf-8")


def verify() -> None:
    gradle_files = [
        ANDROID / "app" / "build.gradle.kts",
        ANDROID / "app" / "build.gradle",
    ]
    gradle = next((path for path in gradle_files if path.exists()), None)

    if gradle is None:
        fail("Gradle file missing during verification")

    gradle_text = gradle.read_text(encoding="utf-8")
    if APP_ID not in gradle_text:
        fail("Application ID was not configured")
    if "minSdk = 23" not in gradle_text and "minSdkVersion 23" not in gradle_text:
        fail("Minimum Android SDK 23 was not configured")

    activity_files = list(
        (ANDROID / "app" / "src" / "main").rglob("MainActivity.*")
    )
    if not activity_files:
        fail("MainActivity missing during verification")

    if APP_ID not in activity_files[0].read_text(encoding="utf-8"):
        fail("MainActivity package was not configured")

    manifest = (
        ANDROID / "app" / "src" / "main" / "AndroidManifest.xml"
    ).read_text(encoding="utf-8")

    if f'android:label="{APP_LABEL}"' not in manifest:
        fail("Application label was not configured")
    if "android.permission.INTERNET" not in manifest:
        fail("Internet permission is missing")

    print("Android configuration verified:")
    print(f"  applicationId: {APP_ID}")
    print(f"  label: {APP_LABEL}")
    print("  minSdk: 23")


def main() -> None:
    if not ANDROID.exists():
        fail("Run flutter create before this script")

    configure_gradle()
    configure_main_activity()
    configure_manifest()
    verify()


if __name__ == "__main__":
    main()
